### ISSUE TITLE
[Bug]: Knjiženje obračuna - dimenzije na doprinosima

### ISSUE THREAD

**Issue by Vesna228** [NPSBeograd/NPS-Support#104]
### Contact Details

nevena.veber@nps.rs

### What happened?

Prilikom obračuna doprinosa, globalna dimenzija se ne prenosi na redove doprinosa. Primer na : (na Crops bazi nije podešeno da se neto radzbija po kategorijama prilikom potvrde. )

primer na CROPS_SB_0210 obračun OBR24-057

**Comment by NevenaMajstorovic** [comment]
PR https://github.com/NPSBeograd/HRM-and-Payroll/pull/370
