### ISSUE TITLE
[Bug]: NPSPyR Historical Positi. Data (51105061)

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#108]
### Contact Details

nevena.veber@nps.rs

### What happened?

Pri pokretanju forme History, sa kartice yapsolenog u delu Dokumenti, forma treba da se popuni sa svakog zaposlenog koji ima  kreiranu karticu dokumenta (Ugovor, Anels, Rešenje, Ostala dokumenta). Trenutne je forma prazna. Za zap Z0005 su kreirana dokumenta koja treba da budu prikazana na formi History.
Polja na formi se popunjavaju sledećim podatkom:

- Šifra zaposlenog
-Ime
-Srednje ime
-Prezime
-Datum raspoređivanja (scheduling date).upisuje se datum od sa date pozicije dokumenta. 
-Broj dokumenta- Delovodni broj
-Tip Acta (Act type). upisuje se Ugovor/Aneks/Rešenje/Ostala dokumenta (u zavisnosti koji tip dokumnta je kreiran
-Document type-automatski se popunjava tip u skladu sa kreiranim dokumentom; (tip Ostala dokumenta) treba dodati
-Šifra radnog nmesta
-Naziv radnog mesta
-Šifra organizacije (Department Code)
-Naziv organizacije(Department Name)
-Sector Code-povlači šifru sektora iz polja nadređena organizacija u šifarniku OJ
-Sektor Name-povlači šifru sektora iz polja nadređena organizacija u šifarniku OJ
-Secton name-upisje nižu OJ
-Koeficijent-ukoliko je definisan
-Cena rada-ukoliko je definisana sa radnog mesta
-Registry Date-datum kreiranja dokumenta
-Od datuma DO datuma
-Podatke povlači sa kartice dokumenta

Testirano na https://businesscentral.dynamics.com/23a9d6c4-1ea0-4ae8-a8c2-77e92da3a391/nps_upg?company=NPS&page=51105073&filter=%27NPSPyR%20Historical%20Positi.%20Data%27.%27Employee%20No.%27%20IS%20%27Z005%27&dc=0&bookmark=C_Jc0LAwCHAg

**Comment by NevenaMajstorovic** [comment]
2024-10-25 VEN: Po dogovoru sa VL deo Istorija - kretanje kroz službu neće biti deo standardnog HR app-a. Taj deo je urađen specifično za RGZ. 
Sa kartice zaposlenog, akcija Dokumenti - Ugovori, Aneksi, Ostala dokumenta sa tih akcija mogu da se vide dokumenti za svakog  zaposlenog.
