### ISSUE TITLE
[Bug]: Brojčana serija aneksa

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#109]
### Contact Details

nevena.veber@nps.rs

### What happened?

Omogućiti kreiranje aneksa kroz brojčanu seriju koja postoji na podešavanju kadrovske. Trenutno pri kreiranju aneksa sistem ne koristi podrazumevanu brojčanu seriju već uvećanje počev od broja 01. U određenom trenutku brojevi počinju da se dupliraju i nije više moguće kreirati kartice aneksa.

### What extentsion are you seeing the problem on?

HRM and Payroll

```[tasklist]
### Tasks
```

**Comment by Tijana251** [comment]
Brojčana serija na Jaffi je rešena po tasku https://navexpress365.sharepoint.com/sites/Customers/KappaStar/Lists/Tasks/DispForm.aspx?ID=170

**Comment by NevenaMajstorovic** [comment]
2024-10-30 VEN: Molim da se napravi primer.

**Comment by Tijana251** [comment]
05.11.2024.Napravljen je primer na razvojoj bazi za zaposlenu Z019. Kada se kreira drugi aneks za zaposlenu, za poziciju 65 i unese vezni dokument na kartici aneks, sistem prijavi grešku da aneks već postoji

**Comment by NevenaMajstorovic** [comment]
Omogućeno kreiranje aneksa kroz brojčanu seriju sa HR podešavanja, proveriti na nps_upg

**Comment by Tijana251** [comment]
pokušavam za zapsolenog 001 da keiram aneks za poziciju 61 ali nešto čudno se dešava. Ne pojavi se pitalica za preuzimanje podataka, pa se pojavi, onda se otvori dokument bez broja...koristim funkciju sa pozicije kreiraj kao-Aneks
