### ISSUE TITLE
[Bug]: Knjiženje i isplata iz obračuna na dobavljače

### ISSUE THREAD

**Issue by Vesna228** [NPSBeograd/NPS-Support#111]
### Contact Details

nevena.veber@nps.rs

### What happened?

Prilikom knjiženja obračuna za 12 mesec broj extermnog dokumenta se razlikuje od incijalnog broja obračuna.
Prilikom isplate obračuna svi iznosi su razbijeni na osnovu dimenzija. Ispraviti za porez i doprinose treba da se kreira samo po jedan red. Primer na NPS_UPG obračun ZAR24-12

**Comment by NevenaMajstorovic** [comment]
Kada se radi predlog uplate po dobavljačima, na request page-u je potrebno čekirati Saberi po dobavljaču i Grupiši po šifri bankovnog računa. Kada su obe kvačice čekirane u nalogu će nastati stavke grupisane po tekućem računu.

**Comment by Vesna228** [comment]
Testirano sa označenim poljima, u redu je, ali je problem učitati podatke samo za jedan obračun.
Potrebno je dodati na formi Predlog uplate dobavljačima polje "Broj dokumenta".

**Comment by Vesna228** [comment]
Testirano, u redu je.
