### ISSUE TITLE
[Bug]: Kreiranje naloga isplatu obustava

### ISSUE THREAD

**Issue by Vesna228** [NPSBeograd/NPS-Support#112]
### Contact Details

nevena.veber@nps.rs

### What happened?

U tabeli NPSPyR Deduction Subtype (51105095) nije označeno polje Group Deduction, a prilikom isplate se kreira zbirni nalog. Molim za ispravku. 
Samo kada je iznačeno polje Group Deduction u nalogu plaćanja se sabiraju obustave po istom kreditoru i istom broju računa.
Primer na SB Crops-a CROPS_SB_1010 obračun ZAR24-010 obustave SUD24-001 i SUD24-003.

**Comment by NevenaMajstorovic** [comment]
2024-10-31 VEN: Ispravljeno je.
