### ISSUE TITLE
[Bug]: Kreiranje prava za plaćeno odusutvo

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#113]
### Contact Details

nevena.veber@nps.rs

### What happened?

Prilikom pokretanja funkcije Automatsko kreiranje prava za plaćeno odsustvo, otvara se forma za unos parametara. Polje Podešavanje kriterijuma (prazan šifarnik, videti na koju kategoriju referencira). Polje šifra delatnosti (takav naziv ne postoji za plaćeno odusutvo) u pitanju je HR radna kategorija.Molim za ispravku.

**Comment by NevenaMajstorovic** [comment]
Polje podešavanje kriterijum referencira na tabelu Podešavanje kriterijum, gleda kriterijume koji imaju Vrstu odsustva Plaćeno odsustvo ili Plaćeno odsustvo dodatno. Trenutno se otvara prazan šifarnik, zato što nije podešena Vrsta odsustva.
Ispravljeno naziv polja Šifra delatnosti da bude HR radna kategorija.

**Comment by Tijana251** [comment]
Kreirano je pravo za plaćeno sa vrstom plaćeno-doatno.Prilikom kreiranja evidencije odsustva za plaćeno odsustvo, u polju podešavanje rada nije moguće uneti šifru kriterijuma. Polje je needitabilno. Molim da se omogući unos.

**Comment by NevenaMajstorovic** [comment]
Na evidenciji odsustva polje Podešavanje rada je dodato kroz dizajn i nije bilo omogućeno uređivanje. Izbacila sam polje na stranicu kroz kod i polje je editabilno.
