### ISSUE TITLE
[Suggestion]: Polje Br. eksternog dokumenta na nalogu za prenos

### ISSUE THREAD

**Issue by pdanica** [NPSBeograd/NPS-Support#114]
### Contact Details

danica.pusicic@nps.rs

### Is your feature request related to a problem? Please describe

Nije moguće dodati polje Br.eksternog dokumenta na zaglavlje naloga za prenos, a dodavanjem kroz uloge polje nije editabilno.

### Describe the solution you'd like

Dodati polje na zaglavlje naloga za prenos, tako da bude vidljivo svima, bez dodavanja kroz personalizaciju.

**Comment by NevenaMajstorovic** [comment]
Zahtev je prihvaćen.
