### ISSUE TITLE
[Bug]: Istorija-kretanje zaposlenog

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#115]
### Contact Details

nevena.veber@nps.rs

### What happened?

Molim da se sa kartice zaposlenog u delu Dokumenti/Istorija, skloni ikonica Istorija, s obzirom da se neće koristiti takav izveštaj.

**Comment by NevenaMajstorovic** [comment]
Potrebno je tabelu 51105061 "NPSPyR Historical Positi. Data" i page 51105073 "NPSPyR Historical Pos. Data" označiti kao obsolete, zato što se neće koristiti.
