### ISSUE TITLE
[Bug]: Prosek zarade

### ISSUE THREAD

**Issue by Vesna228** [NPSBeograd/NPS-Support#116]
### Contact Details

nevena.veber@nps.rs

### What happened?

NPSPyR Income Average (51105214) treba da prikaže radno mesto sa primarne pozicije. Primer na nps_upg zaposleni Z032 prosek za period od 3 meseca počev od 01.08.2024.g

**Comment by OlgaIvljanin** [comment]
Urađeno prema zahtevu, može se testirati na SB nps_upg.
