### ISSUE TITLE
[Bug]: Polje Prati organizaciju na HR podešavanju

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#117]
### Contact Details

nevena.veber@nps.rs

### What happened?

Kada je na HR podešavanju isključeno polje **_Prati organizaciju po datumu_**, pri unosu datuma do na org.jedinici, sistem prijavljuje grešku da postoji aktivna pozicija i da data org jedinica ne može da se zatvori sa  datumom 31.03.2025.
Kada je na HR podešavanju uključeno polje **_Prati organizaciju po datumu_**, pri unosu datuma do na datoj org jedinici sistem prijavljuje grešku _Vrednost u polju datum od ne može biti ručno uneta. Izaberite verziju_. Molim za proveru funkcionalnosti polja Prati organizaciju na HR podešavanju.Primer org.jedinica 010 i zapoleni Z001

**Comment by NevenaMajstorovic** [comment]
U prvom slučaju, kada nije čekirano polje, prilikom unosa Datuma do na org. jedinici, sistem proverava da li postoje aktivne pozicije sa tom sifrom organizacije i ne dozvoljava da se zatvori pozicija ako je Datum do manji nego datum na poziciji.
Proverila sam drugi slučaj, kada je to polje čekirano, sistem uopšte ne dozvoljana da se unosi Datim do na org. jedinici ručno, to je moguće samo ako je isključeno polje.
