### ISSUE TITLE
[Bug]: Broj reporta ta rešenje o jubilarnoj nagradi

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#118]
### Contact Details

nevena.veber@nps.rs

### What happened?

Rešenje o jubilarnoj nagradi je mapirano u reportu broj 51105225. Pri podešavanju tipa dokumenta i šablona za rešenje jub.nagrade u tabeli 51105103 nije moguće izabrati mapirani šablon na 51105225 jer izbor šablona refencira na broj šablona 51105034 Ugovor_Aneks_Rešenje. Molim za ispravku. Primer zaposleni Z001 i broj kartice dokumenta DOC24-002

**Comment by NevenaMajstorovic** [comment]
Omogućeno da se doda i šablon za jubilarne nagrade. Proveriti na nps_upg.
