### ISSUE TITLE
[Suggestion]: Datum isplate

### ISSUE THREAD

**Issue by Vesna228** [NPSBeograd/NPS-Support#120]
### Contact Details

nevena.veber@nps.rs

### Is your feature request related to a problem? Please describe

Na obračunskom listu dodati polje Datum isplate . Polje datum isplate se puni podatkom iz polja "datum isplate" sa obračuna (Calculation)

### Describe the solution you'd like

Na obračunskom listu dodati polje Datum isplate . Polje datum isplate se puni podatkom iz polja "datum isplate" sa obračuna (Calculation)

**Comment by NevenaMajstorovic** [comment]
Zahtev prihvaćen, datum dodati u gornjem desnom uglu.

![image](https://github.com/user-attachments/assets/160b2777-ff6d-493b-a9fe-3887072f5dc0)
