### ISSUE TITLE
[Suggestion]: Predlog uplata dobavljačima

### ISSUE THREAD

**Issue by Sara-nps** [NPSBeograd/NPS-Support#121]
### Contact Details

sarak@nps.rs

### Is your feature request related to a problem? Please describe

Prilikom predloga uplata dobavljačima, BC predlaže za plaćenje avansne fakture.

### Describe the solution you'd like

Potrebno je da se avansne fakture ne nađu u predlogu plaćanja, svejendo je da li će to raditi automatski ili ćemo imati filter na request page-u po stavkama dobavljača gde je moguće izabrati koje se stavke predlažu za plaćanje.

**Comment by 0xEE00** [comment]
Konsultacije sa @IvanaBasara na ovu temu.

**Comment by IvanaBasara** [comment]
Preduslov da se kreira avansna faktura je avansna uplata. Prvo se desila uplata po nekom predracunu ili ponudi, pa nakon toga se kreira avansni račun. Što znači da sada kako predlog uplate radi, bi se duplirala uplata, jer se ona desila kako bi se kreirala avansna faktura. 
Primer je na Trade V2, na dobavljacu C0001160 - Dobavljac 1234. Na sebi ima knjiženu jednu fakturu i jednu avansnu fakturu. Na predlogu se vidi da su predložene obe fakture.

![image](https://github.com/user-attachments/assets/2954c2d7-b1b1-4783-b406-efb875c2b0f8)

Predlog je - da se na Request page doda kvačića koja će omogućiti da se ne predlažu avansne fakture.

**Comment by nemanja899** [comment]
Uradjeno potrebno je testirati.

**Comment by IvanaBasara** [comment]
Radi.
