### ISSUE TITLE
Izveštaj 51105192 Usklađivanje zaposlenih sa pozicijama

### ISSUE THREAD

**Issue by Vesna228** [NPSBeograd/NPS-Support#122]
### Contact Details

nevena.veber@nps.rs

### What happened?

Izmeniti izveštaj na sledeći način: ukoliko zaposleni iima aktivnu poziciju na taj dan, postavlja na Aktivan, u suprotnom u napustio preduzeće (eventualno viditi računa ako je ručno postavljen neki treći status, da ga ne menja)..

**Comment by NevenaMajstorovic** [comment]
Uradjeno prema zahtevu, testirati na nps_upg.

**Comment by Vesna228** [comment]
Testirano, u redu je.
