### ISSUE TITLE
Grupno kreiranje abneksa.vezni dokumnt

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#123]
### Contact Details

nevena.veber@nps.rs

### What happened?

Potrebno je pri kreiranju grupnih aneksa, da se na kreiranim karticama aneksa upiše u polje vezni dokument broj aktivnog ugovora

**Comment by NevenaMajstorovic** [comment]
Prilikom kreiranja grupnih aneksa, već se upisuje broj aktivnog ugovora. Primer na nps_ups, pustila sam izveštaj za zaposlenog Z005: 

![image](https://github.com/user-attachments/assets/f25dc43f-d623-4bb3-a613-c6e411cb655f)

![image](https://github.com/user-attachments/assets/e23b1c36-a0aa-41a2-b5ae-b346a2364f7f)
