### ISSUE TITLE
Povraznik-datum prekida radnog odnosa

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#124]
### Contact Details

nevena.veber@nps.rs

### What happened?

Potrebno je kada se čekira polje Povratnik da se na kartici zapsolenog, tab zaposlenje izbriši podaci: Šifra razloga prekida i datum prestanka. Ovo je slučaj kada se otvara nova pozicija za povratnika.
Inače kada se izbriše datum prestanka na kartici zaposlenog koji je napustio preduzeće, sistem postavlja pitanje da li želite da vratite status u Aktivan. Ova funkcija je omogućena korisnicima, koji pogreše i greškom kliknu da zaposleni odlazi iz preduzeća, s obzirom da HR status nije editabilno polje da bi ručno izmenio

**Comment by NevenaMajstorovic** [comment]
Urađeno je, testirati na nps_upg.

**Comment by Tijana251** [comment]
Testirano.Ok.
