### ISSUE TITLE
[Suggestion]: Štampa Internog računa za avansnu fakturu

### ISSUE THREAD

**Issue by Sara-nps** [NPSBeograd/NPS-Support#125]
### Contact Details

sarak@nps.rs

### Is your feature request related to a problem? Please describe

Štampa internog računa Rep49021051, nije ispravna za avansni račun.

### Describe the solution you'd like

 Iznos PDV u ovom slučaju treba da bude iznos avansne fakture. Takođe, proveriti koji datum se ispisuje u delu datum računa.

**Comment by IvanaBasara** [comment]
Primer je na TRADE V2 - Proknjižene nabavne fakture NKAF23-00015 ∙ NPS D.O.O. BEOGRAD

Ovo je Avansna reverzna faktura na kojoj se prikatuje iznos samo PDV-a. Kada se koristi izvestaj Interni racun potrebno je da prikaze iznos pdv od 400,00 rsd kako je i uradjeno na avnsnom racunu, jer se na avansnom računu prikazuje samo iznos PDV.

![image](https://github.com/user-attachments/assets/9be12bf3-f557-46aa-a5d0-a945b70b2f5f)

Izveštaj ce sada da prikaze 20% na iznos PDV koji je prikazan na racunu (400,00 rsd)

![image](https://github.com/user-attachments/assets/d8b25aae-6e94-4160-993b-8f9928d6b88e)

* Napomena - Izvestaj se koristi kod Nabavne fakture sa reverznim PDV. Tu se dobro prikazuje iznos PDV na izvestaju, jer podatke tj osnovicu uzima sa dokumenta i na njega izracunava 20% PDV. Na primeru gore uzima iznos PDV na koji obracunava PDV.
