### ISSUE TITLE
[Suggestion]: Štampa izdvajanja sa zaliha

### ISSUE THREAD

**Issue by Sara-nps** [NPSBeograd/NPS-Support#126]
### Contact Details

sarak@nps.rs

### Is your feature request related to a problem? Please describe

Standardna štampa ima određene nedostatke. 

### Describe the solution you'd like

Treba da se vidi datum prestanka važenja sa praćenja,  ceo naziv artikla i treba dodati ime i adresu kupca, kao i alternativnu adresu ako postoji.

**Comment by IvanaBasara** [comment]
Primer na Trade V2
Izdvajanje sa zaliha∙ PRBRSKZAL00005

U ovireno crveno veliko je za podatkle o kupcu, a uokvireno pored seriskog broja je polje za rok trajanja

![image](https://github.com/user-attachments/assets/8480d9f3-93ae-471b-8a5d-bbcf929f4503)
