### ISSUE TITLE
Na dobavljaču postoji tekući račun

### ISSUE THREAD

**Issue by Vesna228** [NPSBeograd/NPS-Support#128]
### Contact Details

nevena.veber@nps.rs

### What happened?

Prilikom knjiženja obračuna greška Zapis u tabeli Broj računa dobavljača već postoji Polja i vrednosti za identikaciju: Br.dobavljača =ZDOB1; Šifra=160-01. Primer na MAGNA SB 20241126, obračun OBR24-136

**Comment by NevenaMajstorovic** [comment]
Ispravljeno, testirati na MAGNA_SB_20241126.

**Comment by Vesna228** [comment]
Testirano. OK
