### ISSUE TITLE
[Bug]: Očekivani datum penzije

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#129]
### Contact Details

nevena.veber@nps.rs

### What happened?

Ukoliko je datum u polju Očekivani datum penzije 2-prema stažu, veći od datuma u polju Oćekivani datum prema starosti, ne ispisivati datum u polju Očekivani datum penzije -2-prema stažu. (Kartica zapsolenog, tab Zaposlenje)

**Comment by Tijana251** [comment]
Preimenovati polja za penziju. Prvo polje nazvati Redovna penzija, drugo polje nazvati Prevremena starosna penzija

**Comment by NevenaMajstorovic** [comment]
Urađeno, testirati na nps_upg.
