### ISSUE TITLE
Dimenzije na obračunu

### ISSUE THREAD

**Issue by Vesna228** [NPSBeograd/NPS-Support#130]
### Contact Details

nevena.veber@nps.rs

### What happened?

Pokretanjem funkcije "Obračunaj sve" dimenzije sa zaglavlja obračuna treba da se "prenesu" na porez, doprinose i na radnu listu. Primer na KSR_DEV bazi obračun PROBA.

**Comment by NevenaMajstorovic** [comment]
Problem je nastao zato što dimenzije sa pozicije nisu bile prenete u tabelu default dimesion. Za KSR je napravljena obrada koja je prenela dimenzije sa pozicije u default dimension tabelu.
