### ISSUE TITLE
[Suggestion]: Odobrenja za servis- Odloženi pdv

### ISSUE THREAD

**Issue by SilvijaMicik** [NPSBeograd/NPS-Support#131]
### Contact Details

silvija.micik@nps.rs

### Is your feature request related to a problem? Please describe

Na odobrenjima za servis potrebno je da postoji mogužnost knjiženja odobrenja za servis sa odloženim pdv-om, kao što postoji u slučaju običnih prodajnih odobrenja, jer u skaldu sa zakonom potrebno je da se odobrenja knjiže sa odloženim pdv-om i tek kada kupac vrati potpisano odobrenje tek tada se realizuje pdv po tom odobrenju.

### Describe the solution you'd like

Potrebno je da postoji funkcionalnost za knjiženje i realizaciju odloženog pdv-a, kao što postoji na običnim prodajnim odobrenjima

### Describe alternatives you've considered

Nije moguće na drugačiji način proknižiti odloćeni pdv na odobrnjima za servis, potrebno je d apostoji funkcionalnost kao u slučaju običnih odobrenja, d abi mogao da se realizuje pdv po tom odobrenju.

**Comment by IvanaBasara** [comment]
Na pregledu satvki PDV, treba da se omoguci da mogu da se izvuku polje neralizovana osnovica i neralizovani PDV - ovo je kod odobrenja za servis. Ja sam ih zvukla kroz dizajn, ali treba da se omoguci da moze kroz presonalizaciju. Ova polja ne treba uvek da se vidi nego kome kad treba da moze da izvuce kroz personalizaciju.

![Image](https://github.com/user-attachments/assets/5ccb8b2b-fff7-4df6-b908-6ca9e6427196)
