### ISSUE TITLE
[Suggestion]: Slanje obr.lista na e-mail

### ISSUE THREAD

**Issue by Vesna228** [NPSBeograd/NPS-Support#135]
### Contact Details

nevena.veber@nps.rs

### Is your feature request related to a problem? Please describe

Na zaposlenom dodati ček polje Šalji na privatni email. U zavisnosti od ovog podešavanja potrebno je omogućiti slanje obračunskog lista  i PPP PO obrasca.

### Describe the solution you'd like

Podrazumevano email se šalje na poslovni email, a sa ovim podešavanjem imamo mogućnost da na kartici zaposlenog izaberemo da li želimo da šaljemo na privatni email.

**Comment by NevenaMajstorovic** [comment]
Urađeno, testirati na nps_upg. Na HR kartici zaposlenog dodata kvačica Šalji na privatni mejl, ako je ovo čekirano zaposlenom se email poruke šalju na privatni email, u suprotnom na poslovni.

**Comment by Vesna228** [comment]
Testirano je , u redu je
