### ISSUE TITLE
Podatak za mapiranje grad zaposlenog

### ISSUE THREAD

**Issue by Tijana251** [NPSBeograd/NPS-Support#138]
### Contact Details

tijana.petrovic@nps.rs

### What happened?

Dodati u report 51105034 grad zaposlenog za mapiranje, sa taba Opšti podaci na kartici zaposlenog

### What extentsion are you seeing the problem on?

HRM and Payroll

**Comment by NevenaMajstorovic** [comment]
Dodat grad zaposlenog na izvestaju.
