### ISSUE TITLE
[Suggestion]: Štampa proknjižene isporuke zaliha

### ISSUE THREAD

**Issue by nikolam1** [NPSBeograd/NPS-Support#139]
### Is your feature request related to a problem? Please describe

Pošto standardno ne postoji report za izbor u slučaju dokumenta ''posted inventory shipment'', trebalo bi istu napraviti u lokalizaciji. Predlog izgleda je u prilogu tako da se iskoristi postojeca stampa sales shipment-a, uz izmene prema nacrtu.
[document (1).pdf](https://github.com/user-attachments/files/18127274/document.1.pdf)

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by 0xEE00** [comment]
Dorada privaćena. Rok je 27.12.2024.
