### ISSUE TITLE
[Suggestion]: E-fakture, povezivanje porudžbine/fakture sa ulaznim dokumentom i kontrola statusa

### ISSUE THREAD

**Issue by Sara-nps** [NPSBeograd/NPS-Support#86]
### Contact Details

sarak@nps.rs

### Is your feature request related to a problem? Please describe

Nedostatak ovih kontrola može dovesti do grešaka prilikom knjiženja.

### Describe the solution you'd like

1. Prilikom izbora ulaznog dokumenta sa nabavne porudžbine/fakture potrebno je da postoji kontrola dobavljača. Trenutno je moguće izabrati bilo koji ulazni dokument i proknjižiti fakturu.
2. Nakon što je porudžbina/faktura povezana sa ulaznim dokumentom, prilikom knjiženja je poterbno proveriti status nabavne e-fakture. Trenutno je moguće proknjižiti nabavnu fakturu iako nije odobrena na SEF-u.

**Comment by 0xEE00** [comment]
Urađena naknadna zabrane vezivanja nabavnih dokumenata na ulazni dokument ukoliko nabavna e faktura nije odobrena.
Za sada se neće raditi dodatno ograničenje po dobavljaču.

**Comment by Sara-nps** [comment]
[like]  Sara Kovačević reacted to your message:
________________________________
