### ISSUE TITLE
[Suggestion]: Šifra primaoca isporuke na prodajnim odobrenjima i povratima

### ISSUE THREAD

**Issue by Sara-nps** [NPSBeograd/NPS-Support#95]
### Contact Details

sarak@nps.rs

### Is your feature request related to a problem? Please describe

Na prodajnom odobrenju i nalogu za povrat prodatog nije moguće uneti šifru primaoca isporuke.

### Describe the solution you'd like

Dodati polje šifra primaoca isporuke (Ship-to Code (12)) na prodajno odobrenje i nalog za povrat prodatog i okviru taba isporuka i fakturisanje. Ovo polje treba da bude editabilno.

**Comment by nemanja899** [comment]
Zavrseno, potrebno je testirati

**Comment by Sara-nps** [comment]
Gde mogu da testiram?
