### ISSUE TITLE
[Suggestion]: Blaganja - Unaređenja u radu sa dokumentaima

### ISSUE THREAD

**Issue by nikolam1** [NPSBeograd/NPS-Support#96]
### Contact Details

nikola@nps.rs

### Is your feature request related to a problem? Please describe

Izmena u poljima i akcijama koje se pokrecu sa dokumenata

### Describe the solution you'd like

1. Na page NPS Cash Desk Account List (49021206, List) - treba standardno da bude prikazano polja Balance i Balance LCY (proveriti da li se u ovo polje na listi popujnjava balance amount, primeceno je da se amount vidi na kartici ali isto to polje na listi blagajni je =0)
2. Na page NPS Cash Desk Account List (49021206, List) - razmotriti da se na komande ''uplata, isplata gotocine i dnevnik blagajne'' doda reč '''kreiraj'' ispred naziva akcije. 
![image](https://github.com/user-attachments/assets/01d9dd20-1093-47c8-a19c-7ed9f48e7d59)

3. Na page NPS Cash Desk Account List (49021206, List) - dodati akcije ''dnevnici blagajne'' u okviru taba ''povezano'' > Blagajna.
da ne bi morali da otvaramo karticu blagajne da bi pokrenuli akciju.

**Comment by nemanja899** [comment]
Uradjeno, potrebno je testirati.

**Comment by nikolam1** [comment]
Testirano ok
